version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: book_admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: book_reviews_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://book_admin:pass123@db:5432/book_reviews_db
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app

volumes:
  db_data:
